module.exports = {
    tableName: 'coconutproject',
    columnNames: {
      id: 'uuid',
      reportDate: 'report_date',
      nameOfFiberCrops: 'name_of_fiber_crops',
      region: 'region',
      province: 'province',
      district: 'district',
      municipality: 'municipality',
      barangay: 'barangay',
      nameOfBeneficiary: 'name_of_beneficiary',
      birthdate: 'birthdate',
      age: 'age',
      gender: 'gender',
      category: 'category',
      areaPlantedHas: 'area_planted_has',
      variety: 'variety',
      noOfSeedDerivedPMDistributed: 'no_of_seed_derived_pm_distributed',
      remarks: 'remarks',
    },
  };