module.exports = {
  tableName: 'cocoon',
  columnNames: {
    id: 'uuid',
    reportDate: 'report_date',
    completeNameOfCooperatorOrganization: 'complete_name_of_cooperator_organization',
    region: 'region',
    province: 'province',
    district: 'district',
    municipality: 'municipality',
    barangay: 'barangay',
    age: 'age',
    birthdate: 'birthdate',
    gender: 'gender',
    category: 'category',
    noOfBoxReared: 'no_of_box_reared',
    dateOfRearing: 'date_of_rearing',
    totalProductionInKg: 'total_production_in_kg',
    valueInPhp: 'value_in_php',
  },
};