module.exports = {
  tableName: 'cotton',
  columnNames: {
    id: 'uuid',
    reportDate: 'report_date',
    nameOfBeneficiary: 'name_of_beneficiary',
    region: 'region',
    province: 'province',
    district: 'district',
    municipality: 'municipality',
    barangay: 'barangay',
    gender: 'gender',
    category: 'category',
    quantityOfCottonSeedsGiven: 'quantity_of_cotton_seeds_given',
    areaPlanted: 'area_planted_ha',
    datePlanted: 'date_planted',
    seedCottonHarvested: 'seed_cotton_harvested',
    variety: 'variety',
    remarks: 'remarks',
  },
};