module.exports = {
  tableName: 'iecmaterials',
  columnNames: {
    id: 'uuid',
    reportDate: 'report_date',
    titleOfIECMaterial: 'title_of_iec_material',
    noOfCopiesDistributed: 'no_of_copies_distributed',
    nameOfTrainee: 'name_of_trainee',
    region: 'region',
    province: 'province',
    district: 'district',
    municipality: 'municipality',
    barangay: 'barangay',
    age: 'age',
    gender: 'gender',
    birthdate: 'birthdate',
    category: 'category',
    dateDistributed: 'date_distributed',
  },
};