module.exports = {
  tableName: 'nursery',
  columnNames: {
    id: 'uuid',
    nurseries: 'nurseries',
    reportDate: 'report_date',
    fundedBy: 'funded_by',
    region: 'region',
    province: 'province',
    district: 'district',
    municipality: 'municipality',
    barangay: 'barangay',
    birthdate: 'birthdate',
    age: 'age',
    coopName: 'name_of_cooperative_individual',
    gender: 'gender',
    establishedDate: 'date_established',
    area: 'area_in_hectares_ha',
    variety: 'variety_used',
    moa: 'period_of_moa',
    remarks: 'remarks',
  },
};