module.exports = {
    tableName: 'pmsurvived',
    columnNames: {
      id: 'uuid',
      reportDate: 'report_date',
      plantingMaterials: 'type_of_planting_materials',
      cooperative: 'name_of_cooperative_individual',
      region: 'region',
      province: 'province',
      district: 'district',
      municipality: 'municipality',
      barangay: 'barangay',
      pmestablishment: 'no_of_pm_available_during_establishment',
      variety: 'variety',
      dateReceived: 'date_received',
      pmPlanted: 'no_of_pm_planted',
      pmSurvived: 'no_of_pm_survived',
      remarks: 'remarks',
    },
  };