module.exports = {
  tableName: 'training',
  columnNames: {
    id: 'uuid',
    reportDate: 'report_date',
    training: 'conduct_of_training',
    region: 'region',
    province: 'province',
    district: 'district',
    municipality: 'municipality',
    barangay: 'barangay',
    gender: 'gender',
    ageGroup: 'age_group',
    venue: 'venue',
    startDate: 'start_date',
    endDate: 'end_date',
    participants: 'participants',
    remarks: 'remarks',
  },
};